name: changeclip
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - boltons=23.0.0=py38h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_1
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2023.7.22=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda-package-handling=2.2.0=py38h06a4308_0
  - conda-package-streaming=0.9.0=py38h06a4308_0
  - cryptography=41.0.3=py38hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py38h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - freexl=1.0.6=h27cfd23_0
  - gdal=3.6.2=py38h0daa840_3
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=h2a26cda_1
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json-c=0.16=h5eee18b_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - kealib=1.5.0=hd940352_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=ha8e66a6_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.2.10=0
  - libcurand=10.3.3.141=0
  - libcurl=8.2.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgdal=3.6.2=h01ceada_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libkml=1.3.0=h096b73e_7
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libspatialite=4.3.0a=h21ec0d7_23
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.4=hf1b16e4_1
  - libzip=1.8.0=h6ac8c49_1
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.6=py38h417a72b_1
  - mkl_random=1.2.2=py38h417a72b_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.10=h7f8727e_2
  - packaging=23.1=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.42=hebb0a14_0
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.2.1=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pluggy=1.0.0=py38h06a4308_1
  - poppler=22.12.0=h9614445_1
  - poppler-data=0.4.11=h06a4308_1
  - proj=6.2.1=h05a3930_0
  - pycosat=0.6.4=py38h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cpu
  - qhull=2020.2=hdb19cb5_2
  - readline=8.2=h5eee18b_0
  - ruamel.yaml=0.17.21=py38h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py38h5eee18b_1
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tiledb=2.3.3=h77177df_3
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py38h06a4308_0
  - typing_extensions=4.7.1=py38h06a4308_0
  - uriparser=0.9.7=h5eee18b_0
  - urllib3=1.26.16=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xerces-c=3.2.4=h6a678d5_1
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py38h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - addict==2.4.0
      - affine==2.4.0
      - albumentations==1.3.1
      - aliyun-python-sdk-core==2.13.36
      - aliyun-python-sdk-kms==2.16.2
      - appdirs==1.4.4
      - attrs==23.1.0
      - cachetools==5.3.1
      - cityscapesscripts==2.2.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - clip==1.0
      - cmake==3.25.0
      - codecov==2.1.13
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - coverage==7.3.1
      - crcmod==1.7
      - cycler==0.11.0
      - cython==3.0.2
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.3
      - flake8==6.1.0
      - fonttools==4.42.1
      - fsspec==2023.9.1
      - ftfy==6.1.1
      - gitdb==4.0.10
      - gitpython==3.1.36
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.58.0
      - huggingface-hub==0.17.2
      - humanfriendly==10.0
      - imageio==2.31.3
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - iniconfig==2.0.0
      - interrogate==1.5.0
      - jmespath==0.10.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lit==15.0.7
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - matplotlib==3.7.3
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmcv==2.0.1
      - mmengine==0.8.4
      - model-index==0.1.11
      - nibabel==5.1.0
      - nvidia-ml-py==12.535.108
      - nvitop==1.3.1
      - oauthlib==3.2.2
      - opencv-python==4.8.0.76
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.25
      - ordered-set==4.1.0
      - oss2==2.17.0
      - pandas==2.0.3
      - pathtools==0.1.2
      - platformdirs==3.10.0
      - prettytable==3.9.0
      - protobuf==4.24.3
      - psutil==5.9.5
      - py==1.11.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycodestyle==2.11.0
      - pycryptodome==3.19.0
      - pyflakes==3.1.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pyquaternion==0.9.9
      - pytest==7.4.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - qudida==0.0.4
      - rasterio==1.3.9
      - regex==2023.8.8
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rsa==4.9
      - safetensors==0.3.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - setuptools==60.2.0
      - six==1.16.0
      - smmap==5.0.1
      - snuggs==1.4.7
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.2.2
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - timm==0.9.7
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.0.0+cu118
      - torchaudio==2.0.1+cu118
      - torchvision==0.15.1+cu118
      - tqdm==4.65.2
      - triton==2.0.0
      - typing==3.7.4.3
      - tzdata==2023.3
      - wandb==0.15.11
      - wcwidth==0.2.6
      - werkzeug==2.3.7
      - xdoctest==1.1.1
      - yapf==0.40.1
      - yimage==1.1.0
      - zipp==3.16.2
prefix: /home/user/miniconda3/envs/changeclip
